name: New Hut101 Opportunity
description: List a task which someone can sign up to work on!
labels: ["hut101"]
projects: ["alan-turing-institute/319"]

body:
  - type: markdown
    attributes:
      value: |
        The title should contain the name of the original project, plus as short a description of the task as possible.

  - type: input
    id: contact
    attributes:
      label: Original GitHub issue
      description: URL of the issue on the repository (this should contain a technical description of the work to be done)
      placeholder: "https://github.com/user/repo/issues/N"
    validations:
      required: true

  - type: input
    id: mentor-username
    attributes:
      label: Mentor
      description: The GitHub username of the mentor who will be overseeing this task
      placeholder: "@username"
    validations:
      required: true

  - type: textarea
    id: project-overview
    attributes:
      label: Project overview
      description: An approximately two-sentence summary of what the overall project (i.e. the target repository) is about
    validations:
      required: true

  - type: textarea
    id: technologies
    attributes:
      label: Skills / technologies used
      description: A short list of languages, programmes, or frameworks the mentee will be using on this task
      placeholder: "e.g. Python, matplotlib, C++, ..."
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty level
      options:
        - Easy
        - Medium
        - Hard
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        After you have submitted this issue, please do tag it with the appropriate difficulty label.
        
        Thank you so much for submitting a new Hut101 task!
        
        If you have any questions, please feel free to contact one of the organisers.
