name: Check for stale issues

on:
  schedule:
    - cron: "40 1 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - run: ./.github/workflows/check_stale_issues.sh
        env:
          GH_TOKEN: ${{ github.token }}
